# Generated by Django 4.0.4 on 2022-06-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('departamentoNome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('funcionarioId', models.AutoField(primary_key=True, serialize=False)),
                ('funcionarioNome', models.CharField(max_length=500)),
                ('departamento', models.CharField(max_length=500)),
                ('dataAdesao', models.DateField()),
                ('arquivoFoto', models.CharField(max_length=500)),
            ],
        ),
    ]
